services:
  mysql:
    image: public.ecr.aws/ubuntu/mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=1
      - DB_HOST=mysql
      - DB_PASSWORD=password
      - DB_PORT=3306
      - DB_DATABASE=mysql
      - DB_USER=root
    depends_on:
      - mysql
volumes:
  logvolume01: {}
