version: "3"

networks:
  laravel:

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    ports:
      - "9000:9000"
      - "8080:80"
    volumes:
      - ./app:/var/www/html:delegated
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
